#ifndef CSTA_CONST_H
#define CSTA_CONST_H

#define SEQUENCE_TAG 16
#define INTEGER_TAG 2
#define ENUMERATED_TAG 10

typedef enum{
    svcRequest = 1,
    svcResult,
    svcError,
    svcReject
}CSTAapdu_choice;

typedef enum
{
    ALTERNATECALLSID = 1,
    ANSWERCALLSID = 2,
    CALLCOMPLETIONSID = 3,
    CLEARCALLSID = 4,
    CLEARCONNECTIONSID = 5,
    CONFERENCECALLSID = 6,
    CONSULTATIONCALLSID = 7,
    DIVERTCALLSID = 8,
    HOLDCALLSID = 9,
    MAKECALLSID = 10,
    MAKEPREDICTIVECALLSID = 11,
    QUERYDEVICESID = 12,
    RECONNECTCALLSID = 13,
    RETRIEVECALLSID = 14,
    SETFEATURESID = 15,
    TRANSFERCALLSID = 16,
    ASSOCIATEDATASID = 17,
    PARKCALLSID = 18,
    SENDDTMFTONESSID = 19,
    SINGLESTEPCONFSID = 20,
    CSTAEVENTREPORTSID = 21,
    ROUTEREQUESTSID = 31,
    REROUTEREQUESTSID = 32,
    ROUTESELECTREQUESTSID = 33,
    ROUTEUSEDREQUESTSID = 34,
    ROUTEENDREQUESTSID = 35,
    SINGLESTEPTRANSSID = 50,
    ESCAPESERVICESID = 51,
    SYSTEMSTATUSSID = 52,
    MONITORSTARTSID = 71,
    CHANGEMONITORFILTERSID = 72,
    MONITORSTOPSID = 73,
    SNAPSHOTDEVICESID = 74,
    SNAPSHOTCALLSID = 75,
    STARTDATAPATHSID = 110,
    STOPDATAPATHSID = 111,
    SENDDATASID = 112,
    SENDMULTICASTDATASID = 113,
    SENDBROADCASTDATASID = 114,
    SUSPENDDATAPATHSID = 115,
    DATAPATHSUSPENDEDSID = 116,
    RESUMEDATAPATHSID = 117,
    DATAPATHRESUMEDSID = 118,
    FASTDATASID = 119,
    CONCATENATEMESSAGESID = 500,
    DELETEMESSAGESID = 501,
    PLAYMESSAGESID = 502,
    QUERYVOICEATTRIBUTESID = 503,
    REPOSITIONSID = 504,
    RESUMESID = 505,
    REVIEWSID = 506,
    SETVOICEATTRIBUTESID = 507,
    STOPSID = 508,
    SUSPENDSID = 509,
    SYNTHESIZEMESSAGESID = 510,
    RECORDMESSAGESID = 511
} CSTAServices;

#endif // CSTA_CONST_H
